### ISSUE TITLE
Events CRUD operations

### ISSUE THREAD

**Issue by scottluskcis** [urbanengine/UrbanEngineApi#25]
Add CRUD operations for managing events

**Comment by scottluskcis** [comment]
@tylerbhughes please add additional details if any

**Comment by tylerbhughes** [comment]
- [ ] When creating an event we need to do a pre-check to make sure the room is still available for that time as more than one person could be scheduling their workshops at the same time. 

- [ ] I'd like to do an event cancelled endpoint instead of deleting the record from the database. It's fairly common for an event to disappear from the schedule and someone message me asking what happened to it. If we mark it as cancelled and expose that in the GetById and List endpoints then the flyer can show it was cancelled to the user and help alleviate us of some of those questions. I guess in a sense this endpoint becomes just an update endpoint where we mark an isCancelled flag on the record to true. We should also store the date/time the event was cancelled (in UTC for consistency)

- [ ] When getting the list of events it should default to listing all future events but have an optional parameter that lets us get the list for a specific day. So If I just hit the endpoint without any query parameters it would give me all future events but if I put in June 12, 2019 it would give me all events for that day essentially giving us historical data if anyone wants to look that up.

- [ ] Expect all dates coming from inputs to be in UTC. We will be using Moment.js along with React for the front-end so we should be able to easily convert the dates to UTC before sending them to you.
