### ISSUE TITLE
Venues CRUD operations

### ISSUE THREAD

**Issue by PallasStreams** [urbanengine/UrbanEngineApi#48]

**Comment by tylerbhughes** [comment]
We talked about having both a venue and room table. I think this is still a great idea. I will include info about both in this issue since they are very closely related. 

- [ ] List endpoint for rooms should have an optional date input (expect to be UTC) so we can get all venues for a specific date. 

- [ ] If a date is provided in the rooms list input then we need to do only return rooms that are not booked for that date/time slot and are not hidden (see next requirement).

- [ ] In the current openHuntsville we currently have a method to hide/show a venue (room). It's just a database field that we mark true/false. We need to continue to support this in some fachion. If you have a better alternative to approaching this I'm open to ideas. The reason we would need to hide a room from the user is because we rent a space at Huntsville West and in some cases depending on if they rearrange rooms, move people around to help with renting we may gain or lose a room that we can use.
